version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_network
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: laravel_web
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mariadb:latest
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  db_data:
