version: "3"
services:
  # OrangeHRM Application
  orangehrm:
    image: orangehrm/orangehrm:latest
    container_name: orangehrm_app
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=orangehrm_user
      - MYSQL_PASSWORD=orangehrm_password
    depends_on:
      - mysql
    networks:
      - orangehrm-net

networks:
  orangehrm-net:
    driver: bridge

volumes:
  db_data:
