version: '3'

services:
  orangehrm:
    image: bitnami/orangehrm:latest
    ports:
      - 80:8080
      - 443:8443
    environment:
      - ORANGEHRM_DATABASE_HOST=host.docker.internal
      - ORANGEHRM_DATABASE_PORT_NUMBER=3306
      - ORANGEHRM_DATABASE_USER=root
      - ORANGEHRM_DATABASE_PASSWORD=griktvtwi@wss3407
      - ORANGEHRM_DATABASE_NAME=orangehrm

volumes:
  db_data:


