# Source from https://www.masterzendframework.com/docker-development-environment/
---
version: "3"

volumes:
  database_data:
    driver: local

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 3307:3306
    volumes:
      - ./mariadb/migration.sql:/opt/data/migration.sql
      # - ./mariadb/data:/var/lib/mysql

    command: --init-file /opt/data/migration.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Bangkok
