# Source from https://www.masterzendframework.com/docker-development-environment/
---
version: '3'

volumes:
  database_data:
    driver: local

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/migration.sql:/opt/data/migration.sql
    command: --init-file /opt/data/migration.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Bangkok
