version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: griktvtwi@WSS00    # Change this to your desired password
      ACCEPT_EULA: Y

volumes:
  mssql_data:
    driver: local
