version: "3.8"
services:
  sqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqledge
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=kUIJ1ttEiLtAOL23
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
