# Source from https://www.masterzendframework.com/docker-development-environment/
---
version: "3"

volumes:
  database_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
