# Source from https://www.masterzendframework.com/docker-development-environment/
---
version: "3"

volumes:
  database_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./html:/var/www/html
  mariadb:
    container_name: mysql
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb:/opt/data
    command: --init-file /opt/data/migration.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Bangkok
