version: "3.8"

services:
  ftp:
    image: delfer/alpine-ftp-server
    container_name: ftp_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009" # Passive FTP ports
    environment:
      FTP_USER: root # FTP username
      FTP_PASS: 1Uzfeidx # FTP password
      PASV_ADDRESS: "127.0.0.1" # Replace with your server's public IP if needed
      PASV_MIN_PORT: 30000
      PASV_MAX_PORT: 30009
    volumes:
      - .:/home/vsftpd # Use parent directory for FTP files
    restart: unless-stopped
